[TestPattern]
type        = "vecfile"
seed        = 1000
numrandom   = 1
pattern     = "11111111"
bpdelay     = 1
clkdelay    = 433

[Files]
vecfilepath = "out/RCA16.vec"
toppath     = "out/RCA16_sim.v"
outpath     = "out/vsim"

[TestbenchParams]
clockname   = "clk"
timescale   = "1ps/100fs"
clkperiod   = 70
simlength   = 7000